[package]
name = "libskiller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.4", optional = true }
rusb = "0.9.3"

[features]
clap = ["dep:clap"]
